### ISSUE TITLE
Create Git tags for each release

### ISSUE THREAD

**Issue by egor-n** [JcMinarro/Philology#10]
It is a good practice to tie the release artifacts with the Git commit it was created from. Please comsider using Git tags as it is the usual approach.

**Comment by JcMinarro** [comment]
Good idea, I forgot to track releases

**Comment by JcMinarro** [comment]
I have added a tag for every previous release ;)

**Comment by egor-n** [comment]
Perfect! Hope it won't take too much time to release 1.2.0 👍 Thank you!
