### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by Arms-merchants** [JcMinarro/Philology#32]
Hello, I am using the warehouse you opened as a multi-language switch, but I found that the switch under 7.0 did not work. Setting the interceptor did not get the ID of the string, so I would like to ask What is the lowest Android version that can currently be adapted?

**Comment by JcMinarro** [comment]
There is not min Android Version to supported by the library is [API 16](https://github.com/JcMinarro/Philology/blob/dev/buildSrc/src/main/groovy/com/jcminarro/Config.groovy#L6), but it seems an issue with the `AppCompact` library as was reported on #23
