### ISSUE TITLE
 Device replacement under system version 8.0 does not work

### ISSUE THREAD

**Issue by Arms-merchants** [JcMinarro/Philology#33]
Hello, I use the tool you provided to implement multi-language. It works well in 8.0 and above, but on the devices below 8.0, the PhilologyRepository I defined cannot get the id of the string, and the getText method of it has no callback Go to call, it didn't work. Is this something I need to set?

**Comment by JcMinarro** [comment]
As I commented yesterday into your other Issue https://github.com/JcMinarro/Philology/issues/32#issuecomment-598892765 it is caused by some changes on the last version of `AppCompact`, you can check more details on #23
